### ISSUE TITLE
Browsersync doesn't detect new files while active

### ISSUE THREAD

**Issue by VesterDe** [holger1411/understrap#222] opened 2017-01-19 17:54 UTC
I'll probably fix this myself at some point (if it's fixable), but I'm just putting it here to remember and to help others if they experience the issue.

The issue is that while BS is active (so, while gulp watch-bs is active), it will inject new compiled css automatically into the session whenever a .scss file is saved.

It will not do so for files added after gulp watch-bs was run however.

It's a bit nit picky, but a bug nonetheless :)

**Comment by drewpyd85** [comment] 2017-02-07 17:41
Has anyone been able to find a fix for this? I can not get browser sync to automatically reload on .SCSS changes.

I changed the proxy to "localhost/test/" (using xmamp) and after running gulp watch-bs it loads my default browser with the correct site but no reloading upon changes.

**Comment by VesterDe** [comment] 2017-02-07 17:59
Hm, what you're describing should work. The issue here is that if a file is added after watch-bs is run the new file won't trigger the event.

If it's working correctly, your page should not reload on style changes, but should just have its .css reloaded. To make sure that isn't happening at all, change the browserSyncOptions variable in gulpfile.js to true, instead of false. This should then cause a small notification box to appear in the top right corner of your screen when the page loads, saying it's in sync with Browsersync, and then if you edit a .scss/.css file it should say "Injected theme.min.css".

So if that isn't happening, your problem really exists.

I personally don't use xmamp so I don't know if it's a proxy error or not (or if it's maybe just the trailing slash causing the problem). Do you get any console errors in the browser or any additional debug info in in your bash/command prompt, where you run gulp? I presume reloading *does* then show the style changes?

**Comment by drewpyd85** [comment] 2017-02-07 21:15
When I change the the "notify" to "true" it says "connected to browsersync" in the top right corner like you stated.

When I make a change to a scss file, in say _theme.scss and save, the main theme.css does indeed get updated but the website I'm looking at that's connected to browsersync does nothing. When I refresh the page I get the "connected to browsersync" popup again, and my changes are shown like it should.

Its not injecting like its supposed to and I'm not sure how to find the error, i'm not getting any in my command prompt or console.

**Comment by seganaUK** [comment] 2017-02-08 15:39
@drewpyd85 

I don't suppose you've found a solution for this in the last 18 hours have you?

I have the exact same issue.

Whenever I update the _theme.scss (or a _child_theme.scss) the styles are compiled into the minified css file, but the styles aren't injected. I can see in the gulpfile that *.min.css files are being watched but the change just isn't triggering the injection.

If I change a *.php file however than the changes are reflected (although that causes a page reload)

**Comment by holger1411** [comment] 2017-02-08 15:49
One reason could be the "cleancss" task which runs before the theme.css is minified to theme.min.css.
It delets the old theme.min.css, than it creates a new theme.min.css file.
So there is not a real file change, but a new file.

So it works here (for some reason...) but maybe thats might the problem.

To verify it pleas try the following:
Open your gulpfile.js and search for:
`gulp.task('cssnano', ['cleancss'], function(){`

change it to:
`gulp.task('cssnano',  function(){`

**Comment by drewpyd85** [comment] 2017-02-08 19:25
@holger1411 that seemed to work, not sure why its taking about 5 long seconds to inject. Usually its nearly instant.

Oh well, thanks for the help. If anyone else knows a way to speed it up I'm all ears.

**Comment by seganaUK** [comment] 2017-02-09 12:03
@holger1411  I can confirm that for me, the issue is also resolved by removing ['cleancss'], but also suffer from a very slow cssnano...however that's probably more a cssnano issue than anything.

Thanks for the help.

**Comment by holger1411** [comment] 2017-05-16 07:14
cssnano was replaced with cleancss so I close this issue for now.
Thx to ya all!

**Closed by holger1411** 2017-05-16 07:14 UTC
