### ISSUE TITLE
wpautop

### ISSUE THREAD

**Issue by shirokoweb** [holger1411/understrap#549] opened 2018-02-10 16:25 UTC
Would be great to remove bloody wpautop...

ie.
```
remove_filter( 'the_content', 'wpautop' );
remove_filter( 'the_excerpt', 'wpautop' );
```

**Comment by Thomas-A-Reinert** [comment] 2018-02-10 17:55
Can´t speak for @holger1411 but I guess I know what he will answer: "Stick to the standards". I totally feel with you, but that is the expected WordPress standard and therefore shouldn´t be overwritten in a theme that´s trying to stick to those. If you choose to overwrite the default behaviour, yes, you can do that in your functions.php as you mentioned.

I´d rather set this as an option in the customizer though and usually do so. But that would probably also contradict holgers policy to keep the theme as lean as possible without trying to feature everything possible - remember: it´s meant as a starter theme. Not as the next "Divi" or such.

**Comment by Thomas-A-Reinert** [comment] 2018-02-10 17:55
Sorry, hit the wrong button - didn´t want to close it..

**Comment by shirokoweb** [comment] 2018-02-10 18:24
@Thomas-A-Reinert Actually it's more a suggestion rather than an bug (even if somehow related since formating is a nightmare) but I totally understand your point about following WP standards.

On the other hand, having your code filled with empty <p></p> tags between every div will prevent you from formating your theme with Bootstrap css.

For example:
```
<div class="btn-group">
    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
</div>
```
will have a totally different output than

```
<div class="btn-group">
    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
    <br><!-- added by WP -->
    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
</div>
```
How to deal with that other than preventing WP adding it ?

*btw I have no idea why you bring a commercial builder in here, I'm aware it's a starter theme.*

**Comment by Thomas-A-Reinert** [comment] 2018-02-10 18:51
Hi @shirokoweb - I got ya. And I also understood that it´s not some kinda bug introduced by understrap.

Solution is easy doable with CSS only. I assume that you´ll have no content wrapped into breakreturn / paragraph tags _within_ the button tags.
```
.btn-group p,
btn-group br  {
   display: none;
}
```

Thats probably the easiest quick fix, but I´m sure not the most elegant.
Besides, I assume you´re writing that text into the editor in code-editing view, right? Just write that code without line-breaks and the problem is also solved.

Relating to Divi - just wanted to convey that understrap is not meant as a solution that solves everyones needs out of the box or easily (click-)configurable for the usual John Doe. No offense or something else intended. Didn´t know your background, so I just thought that was the easiest way to tell..

**Comment by shirokoweb** [comment] 2018-02-11 17:22
@Thomas-A-Reinert you guessed right, I paste into editor view.
I thought it would be the easyest way to convert html BS4 to WP.
I tried everything, my first guess was line-breaks indeed, but there were none.
The only way I sorted it was using a filter to remove wpautop.
Anyways, Understrap is a great stuff and a big time saver !

*Regarding ET and their commercial stuff, it's all good, I was wondering why, because few days ago I had to assist an NGO to debug their website using that crap with WC.
That said, you gave me an idea actually, replace all et_ stuff with bs4_ in their builder haha*

**Comment by holger1411** [comment] 2018-02-14 08:14
I hate the p tag problem since my first days with WordPress...but @Thomas-A-Reinert is right: Don´t sticking to the WP standards will create more problems than it solves.
Even some attemps to make WP more secure via a theme can result in a ban from the wordpress.org theme repo...

**Closed** 2018-03-02 02:06 UTC
