### ISSUE TITLE
Layout problems

### ISSUE THREAD

**Issue by TomKisielewski** [holger1411/understrap#143] opened 2016-11-20 18:46 UTC
Hi Guys,
I just installed fresh understrap-master and it doesn't look good. I attached two screenshots. If it is only my issue , or I just missed something, please let me know.

![understrap-master](https://cloud.githubusercontent.com/assets/8680052/20465236/c92bca9e-af50-11e6-9507-be47a2cc4082.png)

That below is on "mobile" view
![understrap-master_mobview](https://cloud.githubusercontent.com/assets/8680052/20465237/c92d35be-af50-11e6-8060-4ec917754c25.png)

Another problem is that understrap  0.4.9 hosted on wordpress.org doesn't have  customizer.js and live preview of site title and tag line doesn't work.

Cheers

**Comment by holger1411** [comment] 2016-11-20 19:39
Hi!

Do you see the same behavior on:
https://understrap.com/understrap/
??

**Comment by stef-k** [comment] 2016-11-20 19:42
This is what I get at https://understrap.com/understrap/ (using Google Chrome on Ubuntu 16.04.1)

![selection_001](https://cloud.githubusercontent.com/assets/5731388/20465635/22800ccc-af6a-11e6-95e4-2b9166d9972f.jpg)

**Comment by holger1411** [comment] 2016-11-20 19:49
Seems that @TomKisielewski issue appear if the static frontpage template is in use...but can´t see it here too with that (or any other template) in use...
For me it looks like the padding is missing so that the negative -20px padding on containers move it outside the browser window...
But without the source its hard to tell...

**Comment by TomKisielewski** [comment] 2016-11-20 21:07
I get this on every page, it is not related to browser as I get is also on the other machine windows 10 / chrome and ms edge running on wamp64, previously I took screenshots from firefox on mint. I don't have such problem with understrap downloaded from wordpress.org, just master from github

Below chrome and edge

![capturechromeedge](https://cloud.githubusercontent.com/assets/8680052/20466086/37d6f082-af64-11e6-997e-6c7e6d0e98a6.PNG)

Full screen screenshot chrome

![capturefullscreenchrome](https://cloud.githubusercontent.com/assets/8680052/20466087/37d97d66-af64-11e6-88db-f7f025a25b96.PNG)

I haven't modified any code, just clean installation of master from github. I will try to have a look at it tomorrow after work

**Comment by stef-k** [comment] 2016-11-20 21:17
I just deleted the theme, downloaded as zip and istalled it again. It works without padding problems. 

Do you by any chance have a child theme installed?

**Comment by Ariflaw** [comment] 2016-11-21 07:45
I have same issue too, I check the code the container class and the class is missing if you install the theme for first time.

Because the container use the WP Customize, so this is the problem. WP Customize not have default value, so you must go to the customize to select Container Width and Save that.

Maybe this is the issue for understrap. Because there no have default value for the Container Customize :)

![customize ariflaw just another wordpress site](https://cloud.githubusercontent.com/assets/7199479/20474427/08e47c1e-aff9-11e6-9e80-b972329595f6.png)

**Comment by holger1411** [comment] 2016-11-21 07:58
Ah, okay. Makes sense. And explains why everyone without a fresh WP and UnderStrap install can´ see it.
But the default is set here:
https://github.com/holger1411/understrap/blob/master/inc/customizer.php#L78
seems correct to me...
@stef-k: Can you check this?

**Comment by holger1411** [comment] 2016-11-21 08:06
Okay found here: https://github.com/holger1411/understrap/blob/master/inc/customizer.php#L81
a "," at the end which shouldn´t be there. Maybe that invalidates the whole "add settings" function...(?).
Removed it here:
https://github.com/holger1411/understrap/commit/9b06f55e6afcdb4b2ce2f862818f37db4174a568

**Comment by stef-k** [comment] 2016-11-21 08:15
The last comma in PHP arrays is optional meaning it does not do any harm if it is there or if missing, as reference at [PHP manual](http://php.net/manual/en/language.types.array.php). Though in WordPress coding PHP standards states that should be present after the last array element, [see here](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation).

I do not think this is the problem. Most probably the problem is with theme defaults, I think they are not initialized during theme's installation - initialization. I'll submit a PR setting all defaults promptly :)

**Comment by stef-k** [comment] 2016-11-21 08:53
Tested in my installation by deleting theme's options from database, in first page reload the code now runs checks if the defaults are set. 

I've only included the recent additions made in customizer but feel free to include anything else I've missed. The file is `theme-settings.php` inside `inc` directory.

**Comment by stef-k** [comment] 2016-11-21 10:04
@TomKisielewski  and @Ariflaw this should be fixed now, can you please confirm?

**Comment by TomKisielewski** [comment] 2016-11-21 12:45
Yes, it is fine now, thank you

**Closed** 2016-11-21 12:50 UTC

**Comment by Thomas-A-Reinert** [comment] 2016-11-21 12:51
Ran into the same problem just yesterday setting up a new site with a child-theme and can confirm that it seems to work on all pages, not only the static frontpage-template.

**Comment by Thomas-A-Reinert** [comment] 2016-11-21 15:42
Well, not yet really closed. 

-  single.php / home.php
Doesn´t include any .col- settings after the .row . this results in no padding applied and therefore any text align to the very left/right without neccessary spacing.
- "Creating default object from empty value in ... customizer.php on line 196"

**Comment by stef-k** [comment] 2016-11-21 16:55
`home.php` doesn't need more padding since it has the `container` or `container-fluid` class, additionally the col-* values should be/they are in individual partial templates, responsible to output posts.

 `content-single.php` partial may need some column setting but since I haven't touched it I do not know if it is like this on purpose.

**Comment by Thomas-A-Reinert** [comment] 2016-11-21 17:19
to make myself a little clearer: 

**no padding without .col***
![image](https://cloud.githubusercontent.com/assets/5886977/20492767/5850275e-b016-11e6-92c5-eb54e9f8df5c.png)



**correct padding with .col***
![image](https://cloud.githubusercontent.com/assets/5886977/20492915/f3a8d32c-b016-11e6-9094-665418b02657.png)


This is the case with quite some templates or template-partials it seems.

**Comment by holger1411** [comment] 2016-11-21 17:40
single.php and home.php loads `global-templates/left-sidebar-check` which does the sidebar check and calculates the col-* values for the primary container
Check if your home/.phpsingle.php include this:
```
<!-- Do the left sidebar check -->
      <?php get_template_part( 'global-templates/left-sidebar-check', 'none' ); ?>
```

and if the corresponding global-templates/left-sidebar-check.php file is there.
I can see the comment:
`<!-- Do the left sidebar check -->`
In your code but nothing follows. Might mean the file is m issing or something is wrong with it

**Comment by Thomas-A-Reinert** [comment] 2016-11-21 22:04
All files are there. Just updated from the latest release a minute ago.
Stock understrap and stock understrap child.

Just some line added to the child css to include another font. Thats it.

**Comment by stef-k** [comment] 2016-11-21 22:20
Can you please test without the child theme in case it is causing regression problems?

**Comment by Thomas-A-Reinert** [comment] 2016-11-24 00:25
Sorry @stef-k and @holger1411 , i´m currently superbusy with my job. Will get back to that problem as soon as I find some time. Prolly over the weekend and no sooner. Sorry.

**Comment by holger1411** [comment] 2016-11-24 08:56
@Thomas-A-Reinert: No problem!
