### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [holger1411/understrap#127] opened 2016-11-14 14:49 UTC
In my humble opinion, the pagination (within articles as well as on archives) looks a bit, ehm, well... Sh*tty? 

My suggestion would be to have it somehow like on my understrap3 demo:
https://test.tarthemes.com/page/2/ (archive) and https://test.tarthemes.com/blog/2013/01/09/markup-text-alignment/ (article).

Will immediately start work on it.

**Comment by Thomas-A-Reinert** [comment] 2016-11-14 15:37
Done. Will be submitted with the next commit in my fork.

**Comment by Thomas-A-Reinert** [comment] 2016-11-17 00:11
Am I right that my updates didnt get merged within the latest release?

**Comment by Thomas-A-Reinert** [comment] 2016-11-17 00:12
Due to conflicts or whatever?

**Comment by holger1411** [comment] 2016-11-17 08:35
Hi!
No, the last stable release is from Oct. 13, your pull request is 3 days old.
There are several merge conflicts so I have to fiddle it out manually.
I will add your changes step-by-step as soon as possible so that they will be included in the next stable release 0.5.0

**Comment by Thomas-A-Reinert** [comment] 2016-11-19 00:55
thanks holger! and sorry for any inconveniences!

**Comment by holger1411** [comment] 2016-11-22 08:51
Hi!
i´am currently trying to embed your pagination function  `understrap_numeric_posts_nav` to the template-tags.php file.
The problem is it did not use the BS4 markup from here:
http://v4-alpha.getbootstrap.com/components/pagination/
and I´am desperately tring to get it into it.
Seems what ever I try it breaks the pagination at some point.

So this:
http://v4-alpha.getbootstrap.com/components/pagination/
has to go into this
http://www.wpbeginner.com/wp-themes/how-to-add-numeric-pagination-in-your-wordpress-theme/

Anyone an idea if and how we could archive this?

**Comment by holger1411** [comment] 2016-11-22 08:58
I add my changes to inc/template-tag.php:
https://github.com/holger1411/understrap/commit/5ff897c03074eee60bc67aae52fe6ca78b12a112
but don´t call the function somewhere. So we can work on it without breaking the core function.
Thats how it looks so far...:
 
![screenshot at nov 22 09-58-00](https://cloud.githubusercontent.com/assets/1568158/20517182/3e1b82b4-b09a-11e6-856f-1831a4bde659.png)

**Comment by stef-k** [comment] 2016-11-22 09:24
I'll check it out and submit a PR...

**Comment by Thomas-A-Reinert** [comment] 2016-11-22 10:02
You´re on it already, @stef-k ? Otherwise I´ll take care about it. Got it working on my local install and should be easy to adapt to bs4´s pagination.

**Comment by stef-k** [comment] 2016-11-22 10:03
I am working on something, when ready i'll create a PR and we'll see...

**Comment by holger1411** [comment] 2016-11-22 15:05
You guys are great!

**Comment by holger1411** [comment] 2016-11-23 09:47
@stef-k:
I moved your PR´s code to its own function into `inc/pagination.php `and apply it to every template file which need it (achive.php, home.php, index.php etc.)

@Thomas-A-Reinert : I tweak your article nav markup/scss a bit and apply it to single.php

**Comment by holger1411** [comment] 2016-11-23 09:48
closed this. Feel free to reopen it if neccessary

**Closed** 2016-11-23 09:47 UTC
Labels: help wanted
